repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: autofix
        name: Auto-fix code (format with isort + black)
        entry: make
        args: [autofix]
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: Lint code (flake8)
        entry: make
        args: [lint]
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: mypy
        name: Type check with mypy
        entry: make
        args: [type-check]
        language: system
        types: [python]
        pass_filenames: false
