# Use curl --data-binary @codecov.yml https://codecov.io/validate to validate changes.
github_checks:
  annotations: false
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default: false

