[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app-size-analyzer"
version = "1.0.0"
description = "CLI tool for analyzing iOS and Android app bundle sizes"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Sentry Team", email = "engineering@sentry.io"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Build Tools",
    "Topic :: System :: Archiving",
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.0",
    "lief>=0.14.0",
    "pydantic>=2.0.0",
    "rich>=13.0.0",
    "typing-extensions>=4.8.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-mock>=3.11.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
    "pre-commit>=3.4.0",
]

[project.scripts]
app-size-analyzer = "app_size_analyzer.cli:main"

[project.urls]
Repository = "https://github.com/getsentry/app-size-analyzer"
Issues = "https://github.com/getsentry/app-size-analyzer/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/app_size_analyzer"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
    "/README.md",
    "/LICENSE",
]

[tool.black]
line-length = 100
target-version = ["py311"]
include = '\\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app_size_analyzer"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = ["lief.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = [
    "--strict-markers",
    "--strict-config",
]