[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "launchpad"
version = "0.1.0"
description = "Sentry service for preprod artifact analysis"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Sentry Team", email = "engineering@sentry.io"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Build Tools",
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.0",
    "flask>=3.0.0",
    "gunicorn>=21.0.0",
    "redis>=5.0.0",
    "kafka-python>=2.0.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "requests>=2.28.0",
    "structlog>=23.0.0",
    "sentry-sdk>=1.40.0",
    "lief>=0.14.0",
    "rich>=13.0.0",
    "typing-extensions>=4.8.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-mock>=3.11.0",
    "pytest-flask>=1.3.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
    "pre-commit>=3.4.0",
    "build>=1.0.0",
    "safety>=2.3.0",
    "bandit>=1.7.0",
    "pip-audit>=2.6.0",
    "types-redis>=4.6.0",
    "types-flask>=1.1.0",
]

[project.scripts]
launchpad = "launchpad.cli:main"
app-size-analyzer = "app_size_analyzer.cli:main"

[project.urls]
Repository = "https://github.com/getsentry/launchpad"
Issues = "https://github.com/getsentry/launchpad/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/launchpad"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
    "/README.md",
    "/LICENSE",
]

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["launchpad"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = ["lief.*", "kafka.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = [
    "--strict-markers",
    "--strict-config",
]
