# Ignored by docker compose, used by devservices
x-sentry-service-config:
  version: 0.1
  service_name: launchpad
  dependencies:
    launchpad:
      description: Service that powers preprod artifact analysis
  modes:
    default: []
    containerized: [launchpad]

x-programs:
  devserver:
    command: make worker

# Below is only relevant when running launchpad as a dependency of the monolith.
services:
  launchpad:
    image: ghcr.io/getsentry/launchpad:nightly
    command:
      - worker
      - --verbose
    environment:
      PYTHONUNBUFFERED: 1
      LAUNCHPAD_ENV: "development"
      SENTRY_BASE_URL: "http://host.docker.internal:8000"
      LAUNCHPAD_RPC_SHARED_SECRET: "launchpad-also-very-long-value-haha"
      LAUNCHPAD_WORKER_RPC_HOST: "host.docker.internal:50051"
      LAUNCHPAD_WORKER_CONCURRENCY: "1"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/health ]"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    platform: linux/amd64
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - devservices
    labels:
      - orchestrator=devservices
    restart: unless-stopped

networks:
  devservices:
    name: devservices
    external: true
