name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.11-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.11-

      # - name: Install devenv
      #   run: |
      #     curl https://raw.githubusercontent.com/getsentry/devenv/main/install-devenv.sh > install-devenv.sh
      #     bash install-devenv.sh

      # - name: Devenv sync
      #   run: ~/.local/share/sentry-devenv/bin/devenv sync

      - name: Install dependencies
        run: make install-dev

      # - name: Create virtual environment
      #   run: python -m venv .venv

      # - name: Install dependencies
      #   run: .venv/bin/pip install -r requirements-dev.txt

      - name: Check code formatting
        run: make check-format

      - name: Run linting checks
        run: make lint

      - name: Run type checking
        run: make type-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      # - name: Install devenv
      #   run: |
      #     curl https://raw.githubusercontent.com/getsentry/devenv/main/install-devenv.sh > install-devenv.sh
      #     bash install-devenv.sh

      # - name: Install dependencies
      #   run: devenv sync

      - name: Install dependencies
        run: make install-dev

      - name: Run unit tests
        run: make test-unit

      - name: Run integration tests
        run: make test-integration

      - name: Test CLI installation and basic functionality
        run: |
          make run-cli ARGS="--help"

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install-dev

      - name: Build package
        run: make build

      - name: Verify build artifacts
        run: |
          ls -la dist/
          .venv/bin/python -m pip install dist/*.whl
          .venv/bin/launchpad --help

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 7
