name: Sentry Dogfooding

on:
  pull_request:
    paths: [src/**, .github/workflows/sentry_dogfood.yml]
  push:
    branches: [main]
    paths: [src/**, .github/workflows/sentry_dogfood.yml]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          fetch-depth: 0

      - name: Install Sentry CLI
        uses: getsentry/action-setup-cli@70d7e587b84c2e78cf4d37cd33d7b74fb3729c1b # v1
        with:
          version: "3.4.1"

      - name: Unzip iOS app
        run: |
          unzip -o ./tests/_fixtures/ios/HackerNews_without_parsedassets.xcarchive.zip
          EXTRACTED_PATH=$(find . -name "*.xcarchive" -type d | head -1)
          mv "$EXTRACTED_PATH" ./HackerNews.xcarchive

      - name: Upload iOS app to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_SENTRY_AUTH_TOKEN }}
        run: |
          sentry-cli --log-level=debug build upload \
            ./HackerNews.xcarchive \
            --org sentry \
            --project launchpad-test-ios \
            --build-configuration Release

      - name: Upload Android app to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_SENTRY_AUTH_TOKEN }}
        run: |
          sentry-cli --log-level=debug build upload \
            ./tests/_fixtures/android/hn.aab \
            --org sentry \
            --project launchpad-test-android \
            --build-configuration Release
